name: Windows Build

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --name=termux_vsbridge termux_vsbridge\run.py

      - name: Prepare VSCode Folder
        run: |
          mkdir dist\.vscode
          mkdir dist\project_file
          Move-Item dist\termux_vsbridge.exe dist\.vscode\termux_vsbridge.exe
          Copy-Item vscode-tasks\tasks-windows.json dist\.vscode\tasks.json
          Copy-Item .vscode\launch.json dist\.vscode\launch.json

      - name: Build ZIP Archive
        run: tar -a -c -f dist\termux_vsbridge.zip -C dist .vscode

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsbridge-windows
          path: dist/termux_vsbridge.zip

      - name: Check if tag exists
        run: |
          if git rev-parse "${{ github.event.inputs.release_version }}" >/dev/null 2>&1; then
            echo "Tag ${{ github.event.inputs.release_version }} already exists"
            exit 1
          fi
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          name: Termux VSBridge - Windows ${{ github.event.inputs.release_version }}
          files: dist/termux_vsbridge.zip
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}